### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [LightIO/LightQ#1]
[Extra null pointer checks are not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null) like the following.
- [broker](https://github.com/rohitjoshi/LightQ/blob/760c34d4be860c46708e69afee4d500b6d3756b5/include/broker.h#L44)
- [consumer](https://github.com/rohitjoshi/LightQ/blob/3650fde19ba04de7a89b2cb5209ea40522ea1d87/include/consumer.h#L61)

**Comment by rohitjoshi** [comment]
Fixed commit [5a556f379df7eb04366161df6db8baa79852efd7](https://github.com/rohitjoshi/LightQ/commit/5a556f379df7eb04366161df6db8baa79852efd7)

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/rohitjoshi/LightQ/commit/5a556f379df7eb04366161df6db8baa79852efd7).
